### ISSUE TITLE
An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by WeihaoLiTW** [aws-samples/reinvent2019-aim362-sagemaker-debugger-model-monitor#2]
Hi,

I am playing train_and_debug.ipynb.  It shows "ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden" when I executed the copying from the S3 bucket.

Can you advise how I deal with it?
Thanks

![Snipaste_2020-02-19_16-57-11](https://user-images.githubusercontent.com/39988920/74818088-fa401880-5338-11ea-9c54-f1e271224556.png)
![Snipaste_2020-02-19_16-57-16](https://user-images.githubusercontent.com/39988920/74818092-fc09dc00-5338-11ea-95c5-6618bd822fd7.png)

**Comment by thisistomdavis** [comment]
Believe the instructions missed out adding permission to read from the 'endtoendmlapp' S3 bucket when you were setting up the IAM role.

You can either edit the attached policies once you've created your SageMaker notebook, or go back and create a new notebook / IAM role and rather than selecting 'None' under 'S3 Buckets you specify', paste 'endtoendmlapp' into the specific bucket option.

Going back and editing the IAM role directly is a little more involved, but if you're familiar-ish with it, you should be able to work out where to add endtoendmlapp/* to the attached S3 policies.

**Comment by emaciek** [comment]
![image](https://user-images.githubusercontent.com/43650/74840583-85181780-5327-11ea-9918-9a6bded39103.png)
![image](https://user-images.githubusercontent.com/43650/74841381-e7bde300-5328-11ea-9252-234210f1cbd6.png)
![image](https://user-images.githubusercontent.com/43650/74841543-205dbc80-5329-11ea-8d34-6c3d01957dcb.png)
![image](https://user-images.githubusercontent.com/43650/74841581-2fdd0580-5329-11ea-874e-cd13da9fc774.png)

Not click edit but "Add ARN" option. Sorry for mistake below.
![image](https://user-images.githubusercontent.com/43650/74841630-42efd580-5329-11ea-9d2a-873f2fcb7cf2.png)

![image](https://user-images.githubusercontent.com/43650/74841674-53a04b80-5329-11ea-8a93-de0c829f39cd.png)

**Comment by meng1932** [comment]
And then I get the following when running on Jupyter notebook.
![image](https://user-images.githubusercontent.com/46638168/74859884-c56e9a00-5315-11ea-9a5b-b089dc791a69.png)

**Comment by WeihaoLiTW** [comment]
thanks, it's fixed and the instruction is super helpful.
